require 'httparty'
require 'football_api/exts/hash'
require 'football_api/exts/object'
require 'football_api/exts/requestable'
require 'football_api/base_request'
require 'football_api/card'
require 'football_api/comment'
require 'football_api/commentary'
require 'football_api/competition'
require 'football_api/errors'
require 'football_api/event'
require 'football_api/fixture'
require 'football_api/goal'
require 'football_api/match'
require 'football_api/match_info'
require 'football_api/match_stats'
require 'football_api/match_summary'
require 'football_api/match_team'
require 'football_api/player'
require 'football_api/standing'
require 'football_api/version'

module FootballApi
end
